markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kangrae Park
tagline:          'A Jekyll theme'
description:      'Department of Mathematical Sciences, Seoul National University'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Kangrae Park'
  url:            https://twitter.com/mdo

paginate:         5

# Conversion



# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
