markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Kangrae Park
tagline:          'mathematics'
description:      'Department of Mathematical Sciences, Seoul National University'
url:              "kangraepark.github.io"
baseurl:          ""

author:
  name:           'Kangrae Park'
  url:            https://twitter.com/mdo

paginate:         5

remote_theme: poole/hyde

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
